### ISSUE TITLE
(-1,8000000000000000,41625574)

### ISSUE THREAD

**Issue by saeidazimi512** [ton-blockchain/wallet-contract-v5#105]
https://explorer.toncoin.org/block?workchain=-1&shard=8000000000000000&seqno=41625574&roothash=2890D41DB76A7FC36AF639B0E07BA5F60C2DFF344BADF469C82D5A840D6B8FF2&filehash=71CFEC45E04DD0665D6E9323FDA29E49AB09651293F781092ED08C5F78A3686A

**Comment by Cabdulaahi6649** [comment]
Solana

**Comment by Cabdulaahi6649** [comment]
Solaana

**Comment by Cabdulaahi6649** [comment]
#119 **_
