### ISSUE TITLE
[Code Fix] Early out of bounced messages

### ISSUE THREAD

**Issue by e6654321** [ton-blockchain/wallet-contract-v5#11]
#9 - Unchecked bounced messages can still go through the sign check process

**Comment by nns2009** [comment]
But bounced messages are already ignored by:

```
if ((op != prefix::extension_action) & (op != prefix::signed_internal)) {
	return (); ;; just receive Toncoins
}

;; bounced messages has 0xffffff prefix and skipped by op check
```

Between, your suggested code doesn't actually do anything, because original comment has a mistake, and it should be 0xffffffff (two more 'f's)

**Comment by tolya-yanot** [comment]
@e6654321 incorrect, there is already a check for valid op;

@nns2009 thanks for finding the mistake in the comment

**Comment by Amirzand62** [comment]
Interface:wallet_V5r1
LT:606012790000001

**Comment by HamiAlyasin54** [comment]
فکر کنم هنوز مشکل حل نشده

**Comment by HamiAlyasin54** [comment]
> Interface:wallet_V5r1
> LT:606012790000001

**Comment by Amirzand62** [comment]
Hello and regards. Excuse me, I am from Iran. I really open every site to
get the bonus gift, the answer is, we cannot support your country. Now what
is my fault in this, what mistake have I made please

در تاریخ چهارشنبه ۲۷ اوت ۲۰۲۵،‏ ۶:۵۸ HamiAlyasin54 ***@***.***>
نوشت:
