### ISSUE TITLE
[Code Fix] Unsafe Whle Loop

### ISSUE THREAD

**Issue by e6654321** [ton-blockchain/wallet-contract-v5#12]
#10 - Unsafe loop condition which could lead to an error upon the Compute Phase

**Comment by nns2009** [comment]
But loop already has:

```
ifnot (cs.slice_refs()) {
  return ();
}
```

**Comment by e6654321** [comment]
> But loop already has:
> 
> 
> 
> ```
> 
> ifnot (cs.slice_refs()) {
> 
>   return ();
> 
> }
> 
> ```

Yes I'm aware. The anti pattern I'm referring to is on doing 'true' inside the while loop. Putting loops without conditions should be avoided.

**Comment by nns2009** [comment]
> Putting loops without conditions should be avoided

Why? Your suggestion just spends extra gas for the extra check, but doesn't affect logic in any way

**Comment by tolya-yanot** [comment]
no problems found
