### ISSUE TITLE
[Code Fix] Reduce code jumps 

### ISSUE THREAD

**Issue by e6654321** [ton-blockchain/wallet-contract-v5#16]
#15 - Reduce jump commands by removing nested if condition for improved storage and gas

**Comment by nns2009** [comment]
Have you tested gas reduction?

It looks to me that it will increase gas costs in the "primary case" (signature is correct): your code will go through two conditions (one of which also has `&`) instead of one

**Comment by tolya-yanot** [comment]
At this development stage, optimisations are not longer acceptable; and it is also debatable whether gas consumption will decrease
