### ISSUE TITLE
Minor optimization suggestions

### ISSUE THREAD

**Issue by akifoq** [ton-blockchain/wallet-contract-v5#26]
I'm late to the deadline but it's also not in the scope of the contest, so there are just a few suggestions for the greater good: 

1. The `throw_unless(error::invalid_c5, cs.slice_refs() == 0);` ([L88](https://github.com/ton-blockchain/wallet-contract-v5/blob/4fab977f4fae3a37c1aac216ed2b7e611a9bc2af/contracts/wallet_v5.fc#L88)) is redundant and can be safely removed (the while loop condition already guarantees that the slice is empty, thus has zero refs).
2. [L99](https://github.com/ton-blockchain/wallet-contract-v5/blob/4fab977f4fae3a37c1aac216ed2b7e611a9bc2af/contracts/wallet_v5.fc#L99) can be replaced with `ifnot (cs~load_int(1)) {`.
3. Lines [181-185](https://github.com/ton-blockchain/wallet-contract-v5/blob/4fab977f4fae3a37c1aac216ed2b7e611a9bc2af/contracts/wallet_v5.fc#L181-L185) can be rephrased as  
```
throw_if(error::invalid_signature, is_external);
return ();
```

These 3 simple optimizations (mainly the third one due to FunC compiler stop emitting `CONT<{...}> EXECUTE` pattern) allow to decrease gas usage for single external transfer from 5049 to 4647 gas units (by 8%).

**Comment by tolya-yanot** [comment]
Not in the context of the contest, but thanks.

3 - resourceful.
