### ISSUE TITLE
Spiderman 

### ISSUE THREAD

**Issue by Asadull77** [ton-blockchain/wallet-contract-v5#29]
![20240706_135121](https://github.com/user-attachments/assets/d626c285-da94-4969-bb59-40b60eae1115)

**Comment by Asadull77** [comment]
![20240706_135122](https://github.com/user-attachments/assets/eddb840c-ffcf-4d05-a5d3-da6abc0e55f5)

**Comment by Asadull77** [comment]
Hi jgfj

**Comment by tolya-yanot** [comment]
spam, ban
