### ISSUE TITLE
[File Structure] Readability Improvements

### ISSUE THREAD

**Issue by e6654321** [ton-blockchain/wallet-contract-v5#8]
The proposed file structure aims to assist the community and other developers in comprehending the contract code more effectively. It also serves as a guideline for maintaining separation of concerns and establishing a cohesive naming convention. Below is the suggested folder structure, including recommended file name casing:

```md
contracts
|── imports
│   ├── stdlib.fc
├── constants.fc
├── library_deployer.fc
├── utils.fc
└── wallet_v5.fc
.
.
wrappers
├── Errors.ts
├── Errors.ts
├── LibraryDeployer.ts
.
.
├── OpCodes.ts
└── WalletV5.ts
.
.
```

**Comment by tolya-yanot** [comment]
thank you, but not planned
